### ISSUE TITLE
请问如何关闭mock，调用后端的api

### ISSUE THREAD

**Issue by arraycto** [mvpyb/vite-vant-template#1]
请问如何关闭mock，调用后端的api

**Comment by mvpyb** [comment]
![image](https://user-images.githubusercontent.com/34262867/167628058-b1f0b149-3e3e-40d6-a39d-1366e90ec2f6.png)
在对应的env文件中添加此变量，值就是你要代理的api地址，，然后下面的 viteMockServe 可以注释掉就行
